### ISSUE TITLE
Ao Criar user trazer um return mais completo

### ISSUE THREAD

**Issue by caio-emidio** [ukecode/ms-middleware-leprechaum#23]
atualmente so recebe (Code: 201 : {})

**Comment by GitAlison** [comment]
Recomendo já trazer O JWT  NA criação do user

**Comment by caio-emidio** [comment]
Como assim trazer o JWT na criacao do user ?

**Comment by GitAlison** [comment]
Ao registrar o usuário... fazer login com os dados fornecidos no mesmo request e retornar o JWT como response do POST

**Comment by caio-emidio** [comment]
Atualmente esta recebendo o objeto q foi criado.
