### ISSUE TITLE
Ao registrar o usuário... fazer login com os dados fornecidos no mesmo request e retornar o JWT como response do POST

### ISSUE THREAD

**Issue by caio-emidio** [ukecode/ms-middleware-leprechaum#26]
Ideia fornecida pelo @GitAlison no - [#23 - Ao Criar user trazer um return mais completo](https://github.com/ukecode/ms-middleware-leprechaum/issues/23) - 

Acredito que antes de fazer devemos discutir a ideia. E entender se eh um ganho muito bom.

Acredito que o que possa ser feito talvez eh criar 2 endpoints
Um que somente cadastra
Um que cadastra e loga.

Sendo assim fica feito e etc.

**Comment by Kaiofprates** [comment]
@caio-emidio É o correto. Dois endpoits distintos.

**Comment by caio-emidio** [comment]
Ja esta feito,

Estarei fechando essa issue ;)
